### ISSUE TITLE
python 2 support

### ISSUE THREAD

**Issue by martinohanlon** [martinohanlon/BlueDot#10]
really?

I know...

but really?

**Comment by martinohanlon** [comment]
First test of using Python 2.

It installs, it runs, but errors when client connects with:

Server started B8:27:EB:CA:C7:71
Waiting for connection
Client connected 68:C4:4D:EC:FD:7A
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bluedot-0.0.4-py2.7.egg/bluedot/server.py", line 130, in _wait_for_connection
    self._read()
  File "/usr/local/lib/python2.7/dist-packages/bluedot-0.0.4-py2.7.egg/bluedot/server.py", line 144, in _read
    except BlockingIOError as e:
NameError: global name 'BlockingIOError' is not defined

**Comment by martinohanlon** [comment]
fixed in 0.0.4
