### ISSUE TITLE
Out of range error results in an exception

### ISSUE THREAD

**Issue by martinohanlon** [martinohanlon/BlueDot#33]
When the client and server can no longer communicate, the server raises an unhandled exception.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bluedot-0.0.7-py3.4.egg/bluedot/server.py", line 139, in _wait_for_connection
    self._read()
  File "/usr/local/lib/python3.4/dist-packages/bluedot-0.0.7-py3.4.egg/bluedot/server.py", line 152, in _read
    data = self._client_sock.recv(1024, socket.MSG_DONTWAIT)
TimeoutError: [Errno 110] Connection timed out
```

The app works fine and recognises the connection is lost.

**Comment by martinohanlon** [comment]
in 0.0.7
