### ISSUE TITLE
Protocol not supported error when using Bluedot on RasPi3

### ISSUE THREAD

**Issue by malynda** [martinohanlon/BlueDot#74]
I am trying to set up BlueDot on my Pi3 for the first time (running Jessie) and I'm encountering an error I haven't yet been able to decipher. I'm also running BerryConda, which is creating all sorts of fun errors.

I was able to run this on my PiZeroW just fine yesterday. (No BerryConda).

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/bluedot/dot.py", line 410, in __init__
    self.start()
  File "/usr/local/lib/python3.4/dist-packages/bluedot/dot.py", line 638, in start
    self._server.start()
  File "/usr/local/lib/python3.4/dist-packages/bluedot/btcomm.py", line 338, in start
    self._server_sock = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
  File "/usr/lib/python3.4/socket.py", line 123, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported

**Comment by martinohanlon** [comment]
What distribution of Python are you using?  BerryConda? Based on the error, Python has been compiled without Bluetooth support.  Obviously without it, BlueDot isnt going to work, my only advise would be to use the 'standard' distribution.
